config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  #resources :users, only: [:index, :show, :new, :create]
  resources :users, only: [:new, :create]
  
  # resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy]
  # 以下はtasks_pathのルーティングを閉じている
  resources :tasks, except: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  # user = User.find(1)
  # user.tasks
  # Task.where(user_id: user.id)
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_tasks = user.tasks.count
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      # redirect_to @user はUsersControllerのshowに飛ぶ
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  # correct_userをshow, edit, update, destroyに適用する。
  # - correct_userを定義する
  # - before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit , :update, :destroy]

  def index
    # @tasks = Task.all
    # @tasks = Task.where(user_id: current_user.id)
    # 現在ログインしているUserが所有しているtaskのみ取得
    @tasks = current_user.tasks
  end

  def show
   # @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    @task.user_id = session[:user_id]
    
    if @task.save
      flash[:success] = 'タスクが正常に登録されました'
      redirect_to @task
    else
      flash.now[:danger] = 'タスクが登録できません'
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(tasks_params)
      flash[:success] = 'タスクは正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'タスクは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @task.destroy
    
    flash[:success] = 'タスクは削除されました'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def tasks_params
    params.require(:task).permit(:content, :status)
  end

  def correct_user
    #...
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @task = current_user.tasks.build  # form_with 用
      @tasks = current_user.tasks.order(id: :desc).page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    #@user = User.find(params[:id])
    ## 今のuser_idと選択しているuser_idが違う場合、root_urlに飛び、returnで返す
    #if @user != current_user
    #  redirect_to root_url and return
    #end
    #@tasks = @user.tasks.order(id: :desc).page(params[:page])
    #counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav>
    <a href="/">Tasks</a>
    
    <div id="navbarSupportedContent">
      <ul></ul>
      <ul>
        <% if logged_in? %>
          <!--li><%= link_to 'Users', users_path %></li-->
          <li>
            <%= current_user.name %><!--a href="#" data-toggle="dropdown"></a-->
            <ul>
              <li><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Signup', signup_path %></li>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= f.label :status, 'ステータス' %>
    <%= f.text_field :status %>
  </div>

  <div>
    <%= f.label :content, 'タスク' %>
    <%= f.text_field :content %>
  </div>

  <%= f.submit '投稿' %>
<% end %>

app/views/tasks/_tasks.html.erb
<ul>
  <% tasks.each do |task| %>
    <li>
      <img src="<%= gravatar_url(task.user, { size: 50 }) %>" alt="">
      <div>
        <div>
          <%= link_to task.user.name, user_path(task.user) %> <span>posted at <%= task.created_at %></span>
        </div>
        <div>
          <p><%= task.content %></p>
        </div>
        <div>
          <% if current_user == task.user %>
            <%= link_to "Delete", task, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate tasks %>
</ul>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> 編集ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', root_path %>

app/views/tasks/index.html.erb
<h1>タスクリスト一覧</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>タスク<%= link_to task.id, task %> :<%= task.status %> &gt; <%= task.content %></li>
  <% end %>
</ul>

<%= link_to '新規タスクの追加', new_task_path %>

app/views/tasks/new.html.erb
<h1>タスクリスト新規作成ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', root_path %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> のメッセージ詳細ページ</h1>

<p>ステータス：<%= @task.status %></p>
<p>タスク：<%= @task.content %></p>

<%= link_to '一覧に戻る', root_path %>
<%= link_to 'このタスクを編集する', edit_task_path(@task) %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul>
    <% users.each do |user| %>
      <li>
        <img src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div>
          <div>
            <%= user.name %>
          </div>
          <!--div>
            <p><%#= link_to 'View profile', user_path(user) %></p>
          </div-->
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div>
  <h1>Sign up</h1>
</div>

<div>
  <div>
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div>
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name %>
      </div>

      <div>
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email %>
      </div>

      <div>
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password %>
      </div>

      <div>
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation %>
      </div>

      <%= f.submit 'Sign up' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!--div>
  <aside>
    <div>
      <div>
        <h3><%#= @user.name %></h3>
      </div>
      <div>
        <img src="<%#= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div>
    <ul>
      <li><a href="<%#= user_path(@user) %>">Tasks</a></li>
      <li><a href="#">Followings</a></li>
      <li><a href="#">Followers</a></li>
    </ul>
    <%#= render 'tasks/tasks', tasks:@tasks %>
  </div>
</div-->